TRUNCATE public.care_site RESTART IDENTITY CASCADE;

TRUNCATE public.cdm_source RESTART IDENTITY CASCADE;

TRUNCATE public.condition_era RESTART IDENTITY CASCADE;

TRUNCATE public.condition_occurrence RESTART IDENTITY CASCADE;

TRUNCATE public.cost RESTART IDENTITY CASCADE;

TRUNCATE public.death RESTART IDENTITY CASCADE;

TRUNCATE public.device_exposure RESTART IDENTITY CASCADE;

TRUNCATE public.location RESTART IDENTITY CASCADE;

TRUNCATE public.measurement RESTART IDENTITY CASCADE;

TRUNCATE public.observation RESTART IDENTITY CASCADE;

TRUNCATE public.observation_period RESTART IDENTITY CASCADE;

TRUNCATE public.payer_plan_period RESTART IDENTITY CASCADE;

TRUNCATE public.person RESTART IDENTITY CASCADE;

TRUNCATE public.procedure_occurrence RESTART IDENTITY CASCADE;

TRUNCATE public.provider RESTART IDENTITY CASCADE;

TRUNCATE public.visit_occurrence RESTART IDENTITY CASCADE;

